# Generated by Django 5.1.6 on 2025-02-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_playerspositions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerspositions',
            options={'managed': False},
        ),
    ]
